backend = "glx";
vsync = true;

#################################
#             Blur
#################################
blur: {
  method = "dual_kawase";
  strength = 3;        # moderate blur - enough to obscure detail, not overkill
};

blur-background = true;
blur-background-fixed = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'slop'",
  "_GTK_FRAME_EXTENTS@"
];

#################################
#      Transparency / Opacity
#################################
active-opacity = 0.85;
inactive-opacity = 0.75;
frame-opacity = 1.0;
inactive-opacity-override = false;




# Transparency rules (optional)
opacity-rule = [
  "100:fullscreen",
  "70:class_g = 'kitty' && focused",       # mostly transparent, still readable
  "55:class_g = 'kitty' && !focused",      # very transparent when not in use
  "80:class_g = 'Rofi'",
  "90:class_g = 'Dunst'",
];
